book_review/book_review/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static


def redirect_to_login(request):
    return redirect("login")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_to_login),
    path("", include("reviews.urls")),  # Inclut les URLs de ton application
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_review/reviews/urls.py
from django.urls import path
from .views import (
    CustomLoginView,
    register,
    home_view,
    custom_logout_view,
    create_review_autonomous,
    create_ticket,
    create_review,
    user_posts_view,
    edit_ticket,
    delete_ticket,
    edit_review,
    delete_review,
    subscription_view,  # Vue pour afficher la page d'abonnement
    follow_user,  # Vue pour suivre un utilisateur
    unfollow_user,  # Vue pour se désabonner d'un utilisateur
    followed_user_posts_view,  # Vue pour afficher les posts d'un utilisateur suivi
    search_users,  # Vue pour la recherche d'utilisateurs
)
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("register/", register, name="register"),
    path("home/", home_view, name="home"),
    path("logout/", custom_logout_view, name="logout"),
    path("ticket/create/", create_ticket, name="create_ticket"),
    path("review/create/<int:ticket_id>/", create_review, name="create_review"),
    path(
        "create_review_autonomous/",
        create_review_autonomous,
        name="create_review_autonomous",
    ),
    path("posts/", user_posts_view, name="user_posts"),
    path("edit_ticket/<int:ticket_id>/", edit_ticket, name="edit_ticket"),
    path("delete_ticket/<int:ticket_id>/", delete_ticket, name="delete_ticket"),
    path("edit_review/<int:review_id>/", edit_review, name="edit_review"),
    path("delete_review/<int:review_id>/", delete_review, name="delete_review"),
    path("subscriptions/", subscription_view, name="subscription"),  # Page d'abonnement
    path(
        "follow/<int:user_id>/", follow_user, name="follow_user"
    ),  # Suivre un utilisateur
    path(
        "unfollow/<int:user_id>/", unfollow_user, name="unfollow_user"
    ),  # Se désabonner
    path(
        "user_posts/<int:user_id>/",
        followed_user_posts_view,
        name="followed_user_posts",
    ),  # Afficher les posts d'un utilisateur suivi
    path(
        "subscriptions/search/", search_users, name="search_users"
    ),  # Recherche d'utilisateurs
]

book_review/reviews/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver

from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/", null=True, blank=True)

    def __str__(self):
        return self.user.username


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, max_length=2048)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="tickets"
    )  # Association à User
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    ticket = models.ForeignKey(Ticket, null=True, blank=True, on_delete=models.SET_NULL)
    headline = models.CharField(max_length=128)
    rating = models.PositiveSmallIntegerField(choices=[(i, str(i)) for i in range(6)])
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reviews")
    time_created = models.DateTimeField(auto_now_add=True)


class Subscription(models.Model):
    follower = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE
    )
    followed = models.ForeignKey(
        User, related_name="followers", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.follower.username} suit {self.followed.username}"

book_review/reviews/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from .models import Review, Ticket


# Formulaire pour la création de tickets
class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ["title", "description", "image"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "image": forms.ClearableFileInput(attrs={"class": "form-control"}),
        }


# Formulaire pour les critiques autonomes (création de tickets et critiques simultanément)
class AutonomousReviewForm(forms.Form):
    # Champs pour le Livre/Article
    ticket_title = forms.CharField(
        label="Titre",
        max_length=128,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    ticket_description = forms.CharField(
        label="Description", widget=forms.Textarea(attrs={"class": "form-control"})
    )
    ticket_image = forms.ImageField(
        label="Image",
        required=False,
        widget=forms.ClearableFileInput(attrs={"class": "form-control"}),
    )

    # Champs pour la Critique
    review_headline = forms.CharField(
        label="Titre de la critique",
        max_length=128,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    review_rating = forms.ChoiceField(
        label="Note", choices=[(i, str(i)) for i in range(6)], widget=forms.RadioSelect
    )
    review_body = forms.CharField(
        label="Commentaire", widget=forms.Textarea(attrs={"class": "form-control"})
    )


# Formulaire pour les critiques
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["headline", "rating", "body"]
        widgets = {
            "headline": forms.TextInput(attrs={"class": "form-control"}),
            "rating": forms.RadioSelect(choices=[(i, str(i)) for i in range(6)]),
            "body": forms.Textarea(attrs={"class": "form-control"}),
        }


# Formulaire d'authentification personnalisé (ajuster si une méthode alternative est utilisée)
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Nom d'utilisateur"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Mot de passe"}
        )
    )


# Formulaire d'inscription personnalisé sans avatar et sans mots de passe
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Adresse email"}
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

book_review/reviews/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from .forms import AutonomousReviewForm, CustomUserCreationForm, TicketForm, ReviewForm
from .models import Ticket, Review, Subscription
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.http import JsonResponse


@login_required
def followed_user_posts_view(request, user_id):
    followed_user = get_object_or_404(User, id=user_id)
    posts = followed_user.posts.all().order_by("-time_created")

    context = {
        "followed_user": followed_user,
        "posts": posts,
    }
    return render(request, "reviews/followed_user_posts.html", context)


@login_required
def search_users(request):
    query = request.GET.get("q", "")
    if query:
        users = User.objects.filter(username__icontains=query).exclude(
            id=request.user.id
        )
        users_data = [{"id": user.id, "username": user.username} for user in users]
        return JsonResponse({"users": users_data})
    return JsonResponse({"users": []})


@login_required
def subscription_view(request):
    query = request.GET.get("q")
    users = User.objects.exclude(username=request.user.username)
    if query:
        users = users.filter(username__icontains=query)

    following = Subscription.objects.filter(follower=request.user)
    following_users = [sub.followed for sub in following]

    context = {
        "users": users,
        "following_users": following_users,
    }
    return render(request, "reviews/subscription.html", context)


@login_required
def follow_user(request, user_id):
    user_to_follow = get_object_or_404(User, id=user_id)
    Subscription.objects.get_or_create(follower=request.user, followed=user_to_follow)

    if request.headers.get("x-requested-with") == "XMLHttpRequest":
        return JsonResponse({"success": True, "username": user_to_follow.username})

    return redirect("subscription")


@login_required
def unfollow_user(request, user_id):
    user_to_unfollow = get_object_or_404(User, id=user_id)
    Subscription.objects.filter(
        follower=request.user, followed=user_to_unfollow
    ).delete()
    return redirect("subscription")


@login_required
def followed_user_posts_view(request, user_id):
    followed_user = get_object_or_404(User, id=user_id)
    tickets = Ticket.objects.filter(user=followed_user).order_by("-time_created")
    reviews = Review.objects.filter(user=followed_user).order_by("-time_created")

    context = {
        "followed_user": followed_user,
        "tickets": tickets,
        "reviews": reviews,
    }
    return render(request, "reviews/followed_user_posts.html", context)


@login_required
def user_posts_view(request):
    tickets = Ticket.objects.filter(user=request.user).order_by("-time_created")
    reviews = Review.objects.filter(user=request.user).order_by("-time_created")

    context = {
        "tickets": tickets,
        "reviews": reviews,
    }
    return render(request, "reviews/user_posts.html", context)


@login_required
def edit_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id, user=request.user)
    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES, instance=ticket)
        if form.is_valid():
            form.save()
            return redirect("user_posts")
    else:
        form = TicketForm(instance=ticket)
    return render(request, "reviews/edit_ticket.html", {"form": form})


@login_required
def delete_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id, user=request.user)
    if request.method == "POST":
        ticket.delete()
        return redirect("user_posts")
    return render(request, "reviews/delete_ticket.html", {"ticket": ticket})


@login_required
def edit_review(request, review_id):
    review = get_object_or_404(Review, id=review_id, user=request.user)
    if request.method == "POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect("user_posts")
    else:
        form = ReviewForm(instance=review)
    return render(request, "reviews/edit_review.html", {"form": form})


@login_required
def delete_review(request, review_id):
    review = get_object_or_404(Review, id=review_id, user=request.user)
    if request.method == "POST":
        review.delete()
        return redirect("user_posts")
    return render(request, "reviews/delete_review.html", {"review": review})


@login_required
def create_review_autonomous(request):
    if request.method == "POST":
        form = AutonomousReviewForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = Ticket.objects.create(
                title=form.cleaned_data["ticket_title"],
                description=form.cleaned_data["ticket_description"],
                image=form.cleaned_data["ticket_image"],
                user=request.user,
            )

            Review.objects.create(
                ticket=ticket,
                headline=form.cleaned_data["review_headline"],
                rating=form.cleaned_data["review_rating"],
                body=form.cleaned_data["review_body"],
                user=request.user,
            )

            return redirect("home")
    else:
        form = AutonomousReviewForm()

    return render(request, "reviews/create_review_autonomous.html", {"form": form})


@login_required
def create_review(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
            return redirect("home")
    else:
        form = ReviewForm()
    return render(
        request, "reviews/create_review.html", {"form": form, "ticket": ticket}
    )


@login_required
def create_ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect("home")
    else:
        form = TicketForm()
    return render(request, "reviews/create_ticket.html", {"form": form})


def custom_logout_view(request):
    logout(request)
    return redirect("login")


class CustomLoginView(LoginView):
    template_name = "reviews/login.html"

    def form_valid(self, form):
        print(f"Authenticating user: {form.get_user()}")
        login(self.request, form.get_user())
        return redirect("/home/")


@login_required
def home_view(request):
    search_query = request.GET.get(
        "q", ""
    )  # Récupérer la recherche depuis les paramètres GET

    # Récupérer tous les tickets et critiques de tous les utilisateurs
    tickets = Ticket.objects.all().order_by("-time_created")
    reviews = Review.objects.all()

    if search_query:
        # Filtrer les tickets et critiques par titre et en-tête si une recherche est spécifiée
        tickets = tickets.filter(title__icontains=search_query)
        reviews = reviews.filter(headline__icontains=search_query)

    # Créer une liste de tickets avec la critique associée si elle existe
    tickets_with_reviews = []
    for ticket in tickets:
        ticket_review = reviews.filter(
            ticket=ticket
        ).first()  # On suppose qu'un seul review par ticket
        tickets_with_reviews.append((ticket, ticket_review))

    # Critiques autonomes
    autonomous_reviews = Review.objects.filter(ticket__isnull=True)

    context = {
        "tickets_with_reviews": tickets_with_reviews,
        "autonomous_reviews": autonomous_reviews,
        "search_query": search_query,  # Passer la recherche dans le contexte
    }
    return render(request, "reviews/home.html", context)


def register(request):
    if request.method == "POST":
        print("Form submitted")
        form = CustomUserCreationForm(request.POST)
        # Suppression de la gestion des fichiers, puisque l'avatar n'est plus utilisé
        if form.is_valid():
            print("Form is valid")
            user = form.save()

            # Authentification basée sur un système alternatif à implémenter ici
            # Exemple : Utilisation de tokens ou autres systèmes

            login(
                request, user
            )  # Assurez-vous que `login` est compatible avec le nouveau système d'authentification.
            return redirect("home")
        else:
            print("Form is not valid")
    else:
        form = CustomUserCreationForm()
    return render(request, "reviews/register.html", {"form": form})

book_review/reviews/templates/reviews/create_review.html
{% extends "base_generic.html" %}

{% block title %}Créer une critique{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/creation.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h2>Créer une critique</h2>
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ ticket.title }}</h5>
            <p class="card-text">{{ ticket.description }}</p>
            {% if ticket.image %}
            <img src="{{ ticket.image.url }}" class="img-fluid rounded" alt="Image du ticket">
            {% endif %}
            <p class="card-text"><small class="text-muted">{{ ticket.time_created|date:"H:i, d M Y" }}</small></p>
        </div>
    </div>
    
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_headline" class="form-label">Titre</label>
            {{ form.headline }}
        </div>
        <div class="mb-3">
            <label for="id_rating" class="form-label">Note</label>
            <div class="rating-stars">
                {% for i in form.rating.field.choices %}
                    <label class="star-rating" for="id_rating_{{ i.0 }}">
                        <input type="radio" name="rating" value="{{ i.0 }}" id="id_rating_{{ i.0 }}" {% if form.rating.value == i.0|stringformat:"s" %}checked{% endif %}>
                        <i class="bi {% if form.rating.value|stringformat:"s" == i.0|stringformat:"s" %}bi-star-fill{% else %}bi-star{% endif %}"></i>
                    </label>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3">
            <label for="id_body" class="form-label">Commentaire</label>
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/create_review_autonomous.html
{% extends "base_generic.html" %}

{% block title %}Créer une critique{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/creation.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %}

{% block content %}
<div class="review-create-container mt-4">
    <h1 class="review-create-title">Créer une critique</h1>
    <form method="post" enctype="multipart/form-data" class="review-create-form">
        {% csrf_token %}
        <div class="review-section">
            <h4 class="review-subtitle">Livre / Article</h4>
            <div class="form-group">
                {{ form.ticket_title.label_tag }}{{ form.ticket_title }}
            </div>
            <div class="form-group">
                {{ form.ticket_description.label_tag }}{{ form.ticket_description }}
            </div>
            <div class="form-group">
                {{ form.ticket_image.label_tag }}{{ form.ticket_image }}
            </div>
        </div>

        <div class="review-section">
            <h4 class="review-subtitle">Critique</h4>
            <div class="form-group">
                {{ form.review_headline.label_tag }}{{ form.review_headline }}
            </div>
            <div class="form-group">
                {{ form.review_rating.label_tag }}
                <div class="rating-stars">
                    {% for i in form.review_rating.field.choices %}
                        <label class="star-rating" for="id_review_rating_{{ i.0 }}">
                            <input type="radio" name="review_rating" value="{{ i.0 }}" id="id_review_rating_{{ i.0 }}" {% if form.review_rating.value == i.0|stringformat:"s" %}checked{% endif %}>
                            <i class="bi {% if form.review_rating.value|stringformat:"s" == i.0|stringformat:"s" %}bi-star-fill{% else %}bi-star{% endif %}"></i>
                        </label>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group">
                {{ form.review_body.label_tag }}{{ form.review_body }}
            </div>
        </div>

        <button type="submit" class="btn btn-custom-submit">Envoyer</button>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/create_ticket.html
{% extends "base_generic.html" %}

{% block title %}Créer un ticket{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/creation.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="ticket-container mt-4">
    <h2>Créer un ticket</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ticket-card mb-3">
            <label for="id_title" class="form-label">Titre</label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description }}
        </div>
        <div class="mb-3">
            <label for="id_image" class="form-label">Image</label>
            {{ form.image }}
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/delete_review.html
{% extends "base_generic.html" %}

{% block title %}Supprimer Critique{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/supprime.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h1 class="h3">Supprimer Critique</h1>
    <p>Êtes-vous sûr de vouloir supprimer cette critique?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Supprimer</button>
        <a href="{% url 'user_posts' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/delete_ticket.html
{% extends "base_generic.html" %}

{% block title %}Supprimer Ticket{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/supprime.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h1 class="h3">Supprimer Ticket</h1>
    <p>Êtes-vous sûr de vouloir supprimer ce ticket?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Supprimer</button>
        <a href="{% url 'user_posts' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/edit_review.html
{% extends "base_generic.html" %}

{% block title %}Modifier Critique{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/modify.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h1 class="h3">Modifier Critique</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Sauvegarder</button>
        <a href="{% url 'user_posts' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/edit_ticket.html
{% extends "base_generic.html" %}

{% block title %}Modifier Ticket{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/modify.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h1 class="h3">Modifier Ticket</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Sauvegarder</button>
        <a href="{% url 'user_posts' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}

book_review/reviews/templates/reviews/follow_user_posts.html
{% extends "base_generic.html" %}

{% block title %}Posts de {{ followed_user.username }}{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/follow.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h1 class="h3">Posts de {{ followed_user.username }}</h1>
    {% for post in posts %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.description }}</p>
                {% if post.image %}
                    <img src="{{ post.image.url }}" class="img-fluid" alt="Image du post">
                {% endif %}
                <p class="card-text"><small class="text-muted">{{ post.time_created|date:"H:i, d M Y" }}</small></p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

book_review/reviews/templates/reviews/followed_user_posts.html
{% extends "base_generic.html" %}

{% block title %}Posts de {{ followed_user.username }}{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/follow.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %} 

{% block content %}
<div class="container mt-4">
    <h1>Posts de {{ followed_user.username }}</h1>

    {% if posts %}
        {% for post in posts %}
            <div class="card mb-3">
                <div class="card-body">
                    {% if post.title %}
                        <h5 class="card-title">{{ post.title }}</h5>
                    {% endif %}
                    {% if post.description %}
                        <p class="card-text">{{ post.description }}</p>
                    {% endif %}
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="img-fluid" alt="Image du post">
                    {% endif %}
                    <p class="card-text"><small class="text-muted">{{ post.time_created|date:"H:i, d M Y" }}</small></p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-center">Cet utilisateur n'a pas encore créé de post.</p>
    {% endif %}
</div>
{% endblock %}

book_review/reviews/templates/reviews/home.html
{% extends "base_generic.html" %}

{% block title %}Accueil{% endblock %}

{% load static %}
{% block background_image %}
background-image: url('{% static "images/home_page.png" %}');
background-size: cover;
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
{% endblock %}

{% block content %}
<div class="home-container">
    <div class="home-card ">
        <div class="mb-4 text-center">
            <a href="{% url 'create_ticket' %}" class="btn btn-custom mx-2">Demander une critique</a>
            <a href="{% url 'create_review_autonomous' %}" class="btn btn-custom mx-2">Créer une critique</a>
        </div>

        <!-- Affichage des tickets et critiques -->
        {% for ticket, review in tickets_with_reviews %}
        <div class="ticket-card neumorph-container mb-4">
            <div class="card-body">
                {% if ticket.image %}
                <div class="ticket-image neumorph-container mb-2">
                    <img src="{{ ticket.image.url }}" class="img-fluid rounded-start" alt="Image du ticket">
                </div>
                {% endif %}
                <div class="card-text">
                <h5 class="card-title">{{ ticket.title }}</h5>
                <p class="card-text">Publié par : <strong>{{ ticket.user.username }} le {{ ticket.time_created|date:"H:i, d M Y" }}</strong></p>
                <p class="card-text">{{ ticket.description }}</p>
                </div>
                {% if ticket.image %}
                <div class="ticket-image neumorph-container mb-2">
                    <img src="{{ ticket.image.url }}" class="img-fluid rounded-start" alt="Image du ticket">
                </div>
                {% endif %}
                

{% if review %}
<div class="review-card neumorph-container mt-3">
    <div class="card-review-answer">
        <h5 class="card-title">{{ review.headline }}</h5>
        <p class="card-text-review">Publié par : <strong>{{ review.user.username }}</strong></p>
        <p class="card-text-review">{{ review.body }}</p>
        <p class="card-text-rating">
            Note:
            <span class="rating-stars">
                {% for _ in "★★★★★"|slice:":review.rating" %}
                    <i class="bi bi-star-fill"></i>
                {% endfor %}
                {% for _ in "☆☆☆☆☆"|slice:"review.rating:" %}
                    <i class="bi bi-star"></i>
                {% endfor %}
            </span>
        </p>
    </div>
</div>
{% else %}
<a href="{% url 'create_review' ticket.id %}" class="btn btn-custom mt-2">Répondre</a>
{% endif %}


                </div>
               
            </div>
        </div>
        {% endfor %}

        <!-- Affichage des critiques autonomes -->
        {% for review in autonomous_reviews %}
        <div class="review-card neumorph-container mb-3">
            <div class="card-body">
                <h5 class="card-title text-success">{{ review.headline }}</h5>
                <p class="card-text"><small class="text-muted">{{ review.time_created|date:"H:i, d M Y" }}</small></p>
                <p class="card-text">Note: {{ review.rating }}</p>
                <p class="card-text">Publié par : <strong>{{ review.user.username }}</strong></p>
                <p class="card-text">{{ review.body }}</p>
                <p class="card-text"><small class="text-muted">{{ review.time_created|date:"H:i, d M Y" }}</small></p>
            </div>
        </div>
        {% endfor %}

        <!-- Affichage message en cas d'absence de résultats -->
        {% if not tickets_with_reviews and not autonomous_reviews %}
        <p class="text-center">Aucun post trouvé pour ce livre.</p>
        {% endif %}
    </div>
</div>

{% endblock %}